# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/ss-unit-test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Make test results directory
      - run: mkdir ~/test-results

      # Run tests
      - run: ./node_modules/.bin/mocha test --recursive --reporter mocha-junit-reporter
        environment:
          MOCHA_FILE: ~/test-results/test-results.xml
        when: always

      # Store test results
      - store_test_results:
          path: ~/test-results

      # Artifact test results
      - store_artifacts:
          path: ~/test-results